### ISSUE TITLE
Live notification

### ISSUE THREAD

**Issue by potatomilk23** [udinsp/tiktok-live-to-telegram-notification#5]
Hi, I'm new to this, and I'm having a bit of trouble.

I followed all the steps, but I'm not sure what I'm doing wrong. The bot keeps saying the user isn't live streaming, but it actually is. Also, I'm not getting any notifications on Telegram. How can I fix this?
![image](https://github.com/udinsp/tiktok-live-to-telegram-notification/assets/108025138/8800de9f-271a-407a-89f5-c6b1aaccd1c9)

**Comment by udinsp** [comment]
Hello, sorry for the inconvenience. It turns out you can no longer use Cheerio, and I've replaced it with Puppeteer. However, the use of RAM is much higher compared to using Cheerio. For now, that's the only assistance I can provide. Thank you.

**Comment by potatomilk23** [comment]
Thanks a ton! You're a lifesaver. I can finally get it to work. It's quite annoying that TikTok notifications aren't functioning properly.
